type Entry {
  teamName: String!
  email: String!
  teamSelections: [String!]!
  fullName: String!
  date: String!
}

type Team {
  id: Int!
  abbreviation: String!
  city: String!
  name: String!
  price: Int!
}

type Query {
  entries: [Entry!]!
  entry: Entry!
  teams: [Team!]!
}
